# This is a basic workflow to help you get started with Actions

name: Rendzio Flutter CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the mvp-dev branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  package_analyzer:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        channel: [ stable ]
        steps:
        # Setup Java environment in order to build the Android app.
        - uses: actions/checkout@v1
        - uses: actions/setup-java@v1
          with:
            java-version: '12.x'
        
        # Setup the flutter environment.
        - uses: subosito/flutter-action@v1
          with:
            channel: 'beta' # 'dev', 'alpha', default to: 'stable'
            # flutter-version: '1.12.x' # you can also specify exact version of flutter
        
        # Get flutter dependencies.
        - run: flutter pub get
        
        # Check for any formatting issues in the code.
        - run: flutter format --set-exit-if-changed .
        
        # Statically analyze the Dart code for any errors.
        - run: flutter analyze .
        
        # Run widget tests for our flutter project.
        - run: flutter test
        
        # # Build apk.
        # - run: flutter build apk
        
        # # Upload generated apk to the artifacts.
        # - uses: actions/upload-artifact@v1
        #   with:
        #     name: release-apk
        #     path: build/app/outputs/apk/release/app-release.apk

        
  android_build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        channel: [ stable ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '12'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle

  ios_build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ macos-latest ]
        channel: [ stable ]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign

  web_build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest]
        channel: [ stable ]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
